sudo: required
services:
  - docker

before_install:
  - docker build -t samuelsalomonv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true samuelsalomonv/docker-react npm run test -- --coverage